version: '3'

services:
  webserver:
    image: orchid-project-frontend-webserver
    container_name: orchid-project-frontend-webserver
    volumes:
#      #    монтируется конфиг nginx для приложения
      - ./public:/app/public
    ports:
      - "8081:80"
